// Generated by https://quicktype.io
//
// To change quicktype's target language, run command:
//
//   "Set quicktype target language"
export interface TableInfo {
  code: string;
  data: (number | null)[];
  length: number;
}
export interface Report {
  Airport: Airport;
  Time: Time;
  Statistics: Statistics;
}

export interface Airport {
  Code: Code;
  Name: string;
}

export enum Code {
  Atl = "ATL",
  Bos = "BOS",
  Bwi = "BWI",
  Clt = "CLT",
  Dca = "DCA",
  Den = "DEN",
  Dfw = "DFW",
  Dtw = "DTW",
  Ewr = "EWR",
  Fll = "FLL",
  Iad = "IAD",
  Iah = "IAH",
  Jfk = "JFK",
  LGA = "LGA",
  Las = "LAS",
  Lax = "LAX",
  Mco = "MCO",
  Mdw = "MDW",
  Mia = "MIA",
  Msp = "MSP",
  Ord = "ORD",
  Pdx = "PDX",
  Phl = "PHL",
  Phx = "PHX",
  SAN = "SAN",
  Sea = "SEA",
  Sfo = "SFO",
  Slc = "SLC",
  Tpa = "TPA",
}

export interface Statistics {
  "# of Delays": OfDelays;
  Carriers: Carriers;
  Flights: Flights;
  "Minutes Delayed": OfDelays;
}

export interface OfDelays {
  Carrier: number;
  "Late Aircraft": number;
  "National Aviation System": number;
  Security: number;
  Weather: number;
  Total?: number;
}

export interface Carriers {
  Names: string;
  Total: number;
}

export interface Flights {
  Cancelled: number;
  Delayed: number;
  Diverted: number;
  "On Time": number;
  Total: number;
}

export interface Time {
  Label: string;
  Month: number;
  "Month Name": MonthName;
  Year: number;
}

export enum MonthName {
  April = "April",
  August = "August",
  December = "December",
  Febuary = "Febuary",
  January = "January",
  July = "July",
  June = "June",
  March = "March",
  May = "May",
  November = "November",
  October = "October",
  September = "September",
}
